apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "outbox-relay.fullname" . }}
  labels: {{- include "outbox-relay.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "outbox-relay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "outbox-relay.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "outbox-relay.fullname" . }}
      securityContext: {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: outbox-relay
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - { name: http, containerPort: {{ .Values.service.targetPort }} }
          env:
            - { name: PORT, value: "{{ .Values.service.targetPort }}" }
            {{- range $k, $v := .Values.config }}
            - { name: {{ $k }}, value: "{{ $v }}" }
            {{- end }}
          livenessProbe:  {{- toYaml .Values.probes.liveness  | nindent 12 }}
          readinessProbe: {{- toYaml .Values.probes.readiness | nindent 12 }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
