apiVersion: v1
kind: Service
metadata:
  name: succession-service
  namespace: talentbridge
  labels: { app.kubernetes.io/name: succession-service, talentbridge.io/domain: workforce-planning }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50202, targetPort: 50202 }]
  selector: { app.kubernetes.io/name: succession-service }
