image: { repository: mattermost/mattermost-team-edition, tag: 9.11.5 }
postgresql: { enabled: true }
ingress:
  enabled: true
  hosts: [{ host: chat.talentbridge.internal }]
mysql: { enabled: false }
