image: { repository: kubeshop/tracetest, tag: v1.5.0 }
postgresql: { enabled: true }
ingress:
  enabled: true
  hosts: [{ host: tracetest.talentbridge.internal }]
config:
  tracing:
    dataStore:
      type: jaeger
      jaeger: { endpoint: http://jaeger-query.observability:16685 }
