contour:
  image: { repository: ghcr.io/projectcontour/contour, tag: v1.30.1 }
  replicas: 2
envoy:
  image: { repository: docker.io/envoyproxy/envoy, tag: v1.31.2 }
  service: { type: LoadBalancer }
ingressClass:
  name: contour
  default: false
