image: { repository: talentbridge/organisation-service, tag: "", pullPolicy: IfNotPresent }
replicaCount: 2
domain: core-hr
service: { type: ClusterIP, port: 50201, targetPort: 50201 }
resources: { requests: { cpu: 100m, memory: 128Mi }, limits: { cpu: 1000m, memory: 512Mi } }
probes:
  liveness:  { httpGet: { path: /healthz, port: 50201 }, initialDelaySeconds: 15, periodSeconds: 20 }
  readiness: { httpGet: { path: /healthz, port: 50201 }, initialDelaySeconds: 5,  periodSeconds: 10 }
serviceAccount: { create: true, annotations: {} }
podLabels: { app.kubernetes.io/name: organisation-service, app.kubernetes.io/part-of: talentbridge, talentbridge.io/domain: core-hr }
podAnnotations: {}
securityContext: { runAsNonRoot: true, runAsUser: 1000, fsGroup: 1000, seccompProfile: { type: RuntimeDefault } }
containerSecurityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: ["ALL"] } }
env: []
envFrom: []
config: { LOG_LEVEL: info, NEO4J_BOLT_URL: bolt://neo4j.databases:7687 }
region: ""
dataResidencyClass: regional
cloud: { provider: "", storageClass: "", ingressClass: "" }
