apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: talentbridge-tools
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/prabhat-roy/TalentBridge.git
        revision: HEAD
        directories:
          - { path: security/* }
          - { path: observability/* }
          - { path: messaging/* }
          - { path: networking/* }
          - { path: databases/* }
          - { path: data/* }
          - { path: supply-chain/* }
          - { path: sustainability/* }
          - { path: edge/* }
          - { path: streaming/* }
          - { path: workflow/* }
          - { path: registry/charts/* }
          - { path: domain-oss/* }
  template:
    metadata:
      name: "talentbridge-tool-{{path.basename}}"
      labels: { project: talentbridge-tools, area: "{{path[0]}}" }
    spec:
      project: default
      source:
        repoURL: https://github.com/prabhat-roy/TalentBridge.git
        targetRevision: HEAD
        path: "{{path}}"
        helm:
          releaseName: "{{path.basename}}"
          valueFiles: ["values.yaml"]
      destination:
        server: https://kubernetes.default.svc
        namespace: "talentbridge-tools"
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
