apiVersion: v1
kind: Service
metadata:
  name: geo-address-service
  namespace: talentbridge
  labels: { app.kubernetes.io/name: geo-address-service, talentbridge.io/domain: platform }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 51013, targetPort: 51013 }]
  selector: { app.kubernetes.io/name: geo-address-service }
