cloud:
  provider: azure
  storageClass: managed-csi
  ingressClass: azure-application-gateway

serviceAccount:
  annotations:
    azure.workload.identity/client-id: "{{ .Values.azure.clientId }}"

podLabels:
  azure.workload.identity/use: "true"
