image: { repository: ghcr.io/projectnessie/nessie, tag: 0.99.0 }
versionStoreType: ROCKSDB
ingress:
  enabled: true
  hosts: [{ host: nessie.talentbridge.internal }]
persistence:
  enabled: true
  storageClass: gp3
  size: 50Gi
