apiVersion: v2
name: feedback-service
description: Continuous feedback (peer/manager)
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies: [{ name: lib-talentbridge, version: 0.1.0, repository: file://../_lib-talentbridge }]
