global:
  identity:
    auth: { issuerBackendUrl: https://keycloak.talentbridge.internal/realms/camunda-platform }
zeebe:           { clusterSize: 3, partitionCount: 3 }
zeebe-gateway:   { replicas: 2 }
operate:         { replicas: 1 }
tasklist:        { replicas: 1 }
optimize:        { replicas: 1 }
identity:        { ingress: { enabled: true, host: camunda.talentbridge.internal } }
elasticsearch:   { master: { replicaCount: 3 } }
