cloud: { provider: aws, storageClass: gp3, ingressClass: alb }
region: eu-west-1
serviceAccount: { annotations: { eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId }}:role/talentbridge-offer-service } }
envFrom: [{ secretRef: { name: offer-service-aws-secrets } }]
