.PHONY: build test run lint tidy docker-build

build:
	go build -o bin/vaccination-record .

test:
	go test ./... -v -race

run:
	go run .

tidy:
	go mod tidy

lint:
	golangci-lint run ./...

docker-build: tidy
	docker build -t talentbridge/vaccination-record:latest .

docker-run:
	docker run --rm -p 50283:50283 --env-file .env talentbridge/vaccination-record:latest
