name: talentbridge_analytics
version: 1.0.0
config-version: 2
profile: talentbridge
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: target
clean-targets: ["target", "dbt_packages"]
models:
  talentbridge_analytics:
    staging:   { +materialized: view, +schema: stg }
    marts:     { +materialized: table, +schema: mart }
    intermediate: { +materialized: ephemeral }
