talentbridge:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres.talentbridge.svc
      user: dbt
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5432
      dbname: talentbridge_warehouse
      schema: public
      threads: 8
    prod:
      type: trino
      host: trino.talentbridge.svc
      port: 8080
      catalog: iceberg
      schema: talentbridge_mart
      threads: 16
