apiVersion: v1
kind: Pod
metadata: { labels: { jenkins: agent } }
spec:
  containers:
    - { name: jnlp, image: jenkins/inbound-agent:latest }
    - { name: tools, image: talentbridge/jenkins-agent:latest, tty: true, command: ["sleep","infinity"] }
    - { name: docker, image: docker:27-dind, securityContext: { privileged: true } }
