apiVersion: v2
name: okr-service
description: Org-wide OKRs (Objectives & Key Results)
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies: [{ name: lib-talentbridge, version: 0.1.0, repository: file://../_lib-talentbridge }]
