apiVersion: v1
kind: Service
metadata:
  name: employee-sso
  namespace: talentbridge
  labels: { app.kubernetes.io/name: employee-sso, talentbridge.io/domain: identity }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50021, targetPort: 50021 }]
  selector: { app.kubernetes.io/name: employee-sso }
