apiVersion: v1
kind: ConfigMap
metadata:
  name: timesheet-service
  namespace: talentbridge
  labels: { app.kubernetes.io/name: timesheet-service, talentbridge.io/domain: time }
data:
  LOG_LEVEL: info
  PORT: "50124"
