zitadel:
  masterkey: change-me-32-bytes-minimum
  configmapConfig:
    ExternalDomain: zitadel.talentbridge.internal
    ExternalSecure: true
    ExternalPort: 443
ingress:
  enabled: true
  hosts: [{ host: zitadel.talentbridge.internal }]
