cloud: { provider: aws, storageClass: gp3, ingressClass: alb }
region: eu-west-1
serviceAccount: { annotations: { eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId }}:role/talentbridge-salary-service } }
envFrom: [{ secretRef: { name: salary-service-aws-secrets } }]
