image: { repository: apachepinot/pinot, tag: 1.2.0 }
zookeeper: { enabled: true }
controller: { replicaCount: 1, persistence: { size: 50Gi, storageClass: gp3 } }
broker:     { replicaCount: 2 }
server:     { replicaCount: 3, persistence: { size: 500Gi, storageClass: gp3 } }
minion:     { replicaCount: 1 }
